"""Apply the PRE-DECLARED bake-off rule (plan.md §4.2, decisions.md D-03) and write the run configs.

Rule, verbatim from plan.md §4.2 / decisions.md D-03 (written before any result): "Choose the config with the best
mean OOF macro-F1. If the top two are within 1 std, take the smaller/faster one." -> compare only the TOP TWO; if they
are within one fold-std and differ in size, take the smaller; if the same size (equally fast), keep the better one.
(A first implementation treated every config within 1 std as tied and let a 5th-ranked model win — that is NOT the
pre-declared rule; fixed, see decisions.md G40.) Paired per-fold differences are reported alongside for transparency.

Writes: configs/model_a.yaml (12 classes), configs/model_b.yaml (yard + documents held out),
        configs/model_b_near.yaml (disruptions held out), configs/WINNER_CV, reports/cv/bakeoff_summary.{json,md}
Usage: python -m src.select_winner
"""
from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import yaml

from src.common import REPORTS, ROOT

PARAMS_M = {"sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2": 118,
            "sentence-transformers/paraphrase-multilingual-mpnet-base-v2": 278,
            "FacebookAI/xlm-roberta-base": 278}
EXPECTED = 6  # 3 backbones x 2 LRs (hard cap)


def main() -> None:
    rows = []
    for f in sorted((REPORTS / "cv").glob("cv-*-lr*.json")):
        if any(t in f.stem for t in ("-hier", "-aug", "-oe")):
            continue  # stretch variants are not part of the bake-off
        s = json.loads(f.read_text())
        b, c = s["best"], s["config"]
        rows.append({"name": f.stem, "model": c["model"], "lr": c["lr"], "params_M": PARAMS_M[c["model"]],
                     "best_epoch": b["epoch"], "oof_macro_f1": b["pooled_macro_f1"],
                     "fold_mean": b["fold_macro_f1_mean"], "fold_std": b["fold_macro_f1_std"],
                     "oof_accuracy": b["pooled_accuracy"], "non_en_acc": b["non_english_accuracy"],
                     "en_acc": b["english_accuracy"], "coarse_acc": b["coarse_accuracy"]})
    df = pd.DataFrame(rows).sort_values("oof_macro_f1", ascending=False).reset_index(drop=True)
    if len(df) != EXPECTED:
        raise SystemExit(f"bake-off incomplete: {len(df)}/{EXPECTED} configs")
    top, second = df.iloc[0], df.iloc[1]
    within = top.oof_macro_f1 - second.oof_macro_f1 <= top.fold_std
    winner = second if (within and second.params_M < top.params_M) else top
    df["top_two"] = df.index < 2

    # paired per-fold comparison of the winner vs every other config (same folds -> paired)
    def fold_f1(name):
        oof = pd.read_csv(REPORTS / "cv" / f"{name}_oof.csv")
        from sklearn.metrics import f1_score
        return oof.groupby("fold").apply(lambda g: f1_score(g.label, g.pred, average="macro"), include_groups=False)

    wf = fold_f1(winner["name"])
    paired = {}
    for n in df.name:
        if n != winner["name"]:
            d = wf - fold_f1(n)
            paired[n] = {"mean_diff": float(d.mean()), "folds_winner_better": int((d > 0).sum()),
                         "folds_tied": int((d == 0).sum()), "n_folds": int(len(d))}

    base = yaml.safe_load((ROOT / "configs" / "base.yaml").read_text())
    common = {**base, "model": winner.model, "lr": float(winner.lr)}
    for name, holdout in [("model_a", []), ("model_b", ["yard_management", "document_processing"]),
                          ("model_b_near", ["shipment_information.disruptions"])]:
        cfg = {**common, "name": name, "holdout_classes": holdout}
        (ROOT / "configs" / f"{name}.yaml").write_text(
            f"# generated by src/select_winner.py from the CV bake-off (winner: {winner['name']})\n" + yaml.safe_dump(cfg, sort_keys=False))
    (ROOT / "configs" / "WINNER_CV").write_text(winner["name"] + "\n")

    tb = json.loads((REPORTS / "cv" / "cv-tfidf-baseline.json").read_text())["best"]
    summary = {"rule": "best pooled OOF macro-F1; if the top two are within 1 fold-std, take the smaller/faster one",
               "winner": winner["name"], "best_raw": top["name"], "top_two_within_1std": bool(within),
               "paired_vs_winner": paired, "configs": df.to_dict(orient="records"), "baseline": tb}
    (REPORTS / "cv" / "bakeoff_summary.json").write_text(json.dumps(summary, indent=2, default=float))
    show = df.assign(model=df.model.str.split("/").str[-1]).drop(columns=["fold_mean"])
    (REPORTS / "cv" / "bakeoff_summary.md").write_text(show.round(3).to_markdown(index=False))
    print(show.round(3).to_string(index=False))
    print(f"\nTF-IDF baseline: OOF macro-F1 {tb['pooled_macro_f1']:.3f} · non-EN acc {tb['non_english_accuracy']:.3f}")
    print(f"top two: {top['name']} ({top.oof_macro_f1:.3f} ± {top.fold_std:.3f}, {top.params_M}M) vs "
          f"{second['name']} ({second.oof_macro_f1:.3f}, {second.params_M}M) · within 1 std: {within} -> WINNER: {winner['name']}")
    for n, p in paired.items():
        print(f"  paired vs {n:18s}: mean fold diff {p['mean_diff']:+.3f} · winner better on {p['folds_winner_better']}/{p['n_folds']} folds")


if __name__ == "__main__":
    main()
